package com.hyra_ai.backend.entity;

import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.FieldDefaults;

import java.time.LocalDateTime;

@Setter
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE)
@Entity
@Table(name = "mega_tasks")
public class MegaTask {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    String id;

    @ManyToOne
    com.hyra_ai.backend.entity.User user;

    @OneToOne
    com.hyra_ai.backend.entity.Media sourceFace;

    @OneToOne
    com.hyra_ai.backend.entity.Media targetVideo;

    @OneToOne
    com.hyra_ai.backend.entity.Media voiceSample;

    @Column(columnDefinition = "TEXT")
    String inputText;

    String status; // PENDING, SWAPPING, VOICING, TRANSCRIBING, MERGING, COMPLETED, FAILED

    Integer progress; // 0-100

    String swapResultUrl; // URL of the mp4 generated by FaceFusion
    String xttsResultUrl; // URL of the wav generated by XTTS
    String srtResultUrl;  // URL of the srt generated by WhisperX
    String finalResultUrl; // URL of the final output video

    @Builder.Default
    LocalDateTime createdAt = LocalDateTime.now();
}
